use_frameworks!

target 'AdvancedPageControl_Example' do
  pod 'AdvancedPageControl', :path => '../'

  target 'AdvancedPageControl_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 7.0'
    pod 'Nimble', '~> 12.0'
  end
end
